CREATE DATABASE GB;
USE GB;

CREATE TABLE Files (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Ext VARCHAR(16) NOT NULL,
    Type ENUM('rom', 'bios') NOT NULL,
    Data LONGBLOB NOT NULL,
    INDEX IX_Files_Type (Type)
);