<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RunAOTCompilation>true</RunAOTCompilation>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\GB\GB.csproj" />
	</ItemGroup>

	<Target Name="DeployWasm" AfterTargets="Publish">
		<ItemGroup>
			<FrameworkFiles Include="$(PublishDir)wwwroot\_framework\**\*" />
		</ItemGroup>

		<Copy SourceFiles="@(FrameworkFiles)" DestinationFiles="@(FrameworkFiles->'..\GB.Frontend\public\wasm\%(RecursiveDir)%(Filename)%(Extension)')" />
	</Target>
</Project>
